# Enable|Disable base commands
# U can create your own plugin with these commands and disable BaseCommands realisation

help=true

# MODERATION

# ban, ban-ip, unban, banlist, tempban
ban=true
ban-ip=true
unban=true
banlist=true
tempban=true

# mute, mute-ip (yes lol), unmute, mutelist, tempmute
mute=true
mute-ip=true
unmute=true
mutelist=true
tempmute=true

# SERVER INFO

server-info=true